spring.datasource.url=jdbc:postgresql://${DB_HOST:thomas.proxy.rlwy.net}:${DB_PORT:13971}/${DB_NAME:railway}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:tmZhLvidLXxBvZzDdAjloIfzrJlsgAib}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}


# spring.datasource.url=jdbc:h2:mem:transport_db
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# # تأجيل إدخال البيانات حتى يتم إنشاء الجداول
# spring.jpa.defer-datasource-initialization=true
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# # تفعيل واجهة التصفح
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# server.port=9090