# spring.datasource.url=jdbc:postgresql://thomas.proxy.rlwy.net:13971/railway
# spring.datasource.username=postgres
# spring.datasource.password=tmZhLvidLXxBvZzDdAjloIfzrJlsgAib
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# server.port=${PORT:8080}


spring.datasource.url=jdbc:h2:mem:transport_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# تأجيل إدخال البيانات حتى يتم إنشاء الجداول
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# تفعيل واجهة التصفح
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=9090