

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


spring.jpa.show-sql=true



spring.datasource.url=jdbc:postgresql://dpg-d86aa7navr4c73dhn96g-a:5432/transportdb
spring.datasource.username=ms6v
spring.datasource.password=qPiXi2WZykfg98hi7eP58dUewqcbffPX

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect