# =========================
# DATABASE CONFIG (RENDER POSTGRESQL)
# =========================

spring.datasource.url=jdbc:postgresql://dpg-d86aa7navr4c73dhn96g-a.virginia-postgres.render.com:5432/transport_db_ossu
spring.datasource.username=ms6v
spring.datasource.password=qPiXi2WZykfg98hi7eP58dUewqcbffPX
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=${PORT:8080}